// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGhML3moT6n0isa33EZncmN8hZRmGpZA',
    appId: '1:830196510520:web:ea38afb3491ad52a279bcd',
    messagingSenderId: '830196510520',
    projectId: 'kintore-5dcc4',
    authDomain: 'kintore-5dcc4.firebaseapp.com',
    storageBucket: 'kintore-5dcc4.appspot.com',
    measurementId: 'G-RM1RE14SWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFsNUsLt7OLhN4Pas_JeD58LOy7qsFEKs',
    appId: '1:830196510520:android:f9f806f52b056cf7279bcd',
    messagingSenderId: '830196510520',
    projectId: 'kintore-5dcc4',
    storageBucket: 'kintore-5dcc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEJkRivSY-ZEBqLHz5YLBftzLOJn8v2Q8',
    appId: '1:830196510520:ios:3ce1466672a91431279bcd',
    messagingSenderId: '830196510520',
    projectId: 'kintore-5dcc4',
    storageBucket: 'kintore-5dcc4.appspot.com',
    iosBundleId: 'com.example.per',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEJkRivSY-ZEBqLHz5YLBftzLOJn8v2Q8',
    appId: '1:830196510520:ios:3ce1466672a91431279bcd',
    messagingSenderId: '830196510520',
    projectId: 'kintore-5dcc4',
    storageBucket: 'kintore-5dcc4.appspot.com',
    iosBundleId: 'com.example.per',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFGhML3moT6n0isa33EZncmN8hZRmGpZA',
    appId: '1:830196510520:web:7b73e9c8a9a27f86279bcd',
    messagingSenderId: '830196510520',
    projectId: 'kintore-5dcc4',
    authDomain: 'kintore-5dcc4.firebaseapp.com',
    storageBucket: 'kintore-5dcc4.appspot.com',
    measurementId: 'G-8BQR479VW7',
  );

}